export const menuItemsData = [
  {
    id: 1,
    name: 'Boiled chicken Lettuce tomatoes',
    info: '200 gm with fresh tomatoes ',
    price: 24,
    img: "/images/boiled-chicken-lettuce-tomatoes.png",
  },
  {
    id: 2,
    name: 'Chicken biryani',
    info: '200 gm chicken with 200gm rice',
    price: 24,
    img: '/images/chicken-biryani.png',
  },
  {
    id: 3,
    name: 'Chicken roll',
    info: '100gm chicken rolled inside whote wheat roti',
    price: 24,
    img: '/images/chicken-roll.png',
  },
  {
    id: 4,
    name: 'Chicken sandwich',
    info: 'Two brown breads with 50gm of chicken',
    price: 24,
    img: '/images/chicken-sandwich.png',
  },
  {
    id: 5,
    name: 'Chocolate bowl (peanut butter & banana)',
    info: 'Oats bowl with peanut butter and banana for weight gain ',
    price: 24,
    img: '/images/chocolate-bowl-(peanut butter & banana).png',
  },
  {
    id: 6,
    name: 'Egg biryani',
    info: '4 eggs & 250gm rice',
    price: 24,
    img: '/images/egg-biryani.png',
  },
  {
    id: 7,
    name: 'Egg roll',
    info: '2 eggs roll with loads of veggies',
    price: 24,
    img: '/images/egg-roll.png',
  },
  {
    id: 8,
    name: 'Green veggie sandwich',
    info: '2 Brown breads with loaded veggies',
    price: 24,
    img: '/images/green-veggie-sandwich.png',
  },
  {
    id: 9,
    name: 'Grilled Chicken',
    info: '250 gm of grilled chicken with lemon',
    price: 24,
    img: '/images/grilled-chicken.png',
  },
  {
    id: 10,
    name: 'Grilled fish',
    info: '250 gm of grilled fish with lemon',
    price: 24,
    img: '/images/grilled-fish.png',
  },
  {
    id: 11,
    name: 'Grilled paneer',
    info: '250 gm of grilled paneer with lemon',
    price: 24,
    img: '/images/grilled-paneer.png',
  },
  {
    id: 12,
    name: 'Grilled paneer sandwich',
    info: 'Grilled brown breads with 100gm of paneer',
    price: 24,
    img: '/images/grilled-paneer-sandwich.png',
  },
  {
    id: 13,
    name: 'Omelette tomatoes ham cheese green veggies',
    info: '3 eggs omeltte with veggies',
    price: 24,
    img: '/images/omelette-tomatoes-ham-cheese-green-veggies.png',
  },
  {
    id: 14,
    name: 'Paneer veggie roll',
    info: '100gm Paneer rolled inside whote wheat roti',
    price: 24,
    img: '/images/paneer-veggie-roll.png',
  },
  {
    id: 15,
    name: 'Sprouted salad',
    info: 'Freshly sprouted moong beans with finely chopped herbs and tomatoes',
    price: 24,
    img: '/images/sprouted-salad.png',
  },
  {
    id: 16,
    name: 'Protein shake (Chocolate)',
    info: '1 scoop of On whey isolate with 300 ml milk ',
    price: 24,
    img: '/images/Protein-shake-(Chocolate).png',
  },
  {
    id: 17,
    name: 'Dry fruit protein shake',
    info: 'almonds, pistachios, cashews, raisins, dates, & saffron',
    price: 24,
    img: '/images/dry-fruit-protein-shake.png',
  },
];
